"""rename department

Revision ID: 174216365b3d
Revises: f98419106f62
Create Date: 2024-10-06 16:00:32.184312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174216365b3d'
down_revision = 'f98419106f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
